// Portfolio, marketplace gigs and real client reviews.
import { FIVERR_URL } from './company.js';

const CDN = 'https://fiverr-res.cloudinary.com';

export const gigs = [
  {
    title: 'I will do accurate data entry, web research and copy paste task',
    url: `${FIVERR_URL}/do-provide-all-type-data-entry-within-24hrs`,
    image: `${CDN}/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/142774291/original/4c2870a5353c3fc6fa09f59f5b84f669666f51a6/do-provide-all-type-data-entry-within-24hrs.jpg`,
    startingPrice: 20, rating: 4.8, reviewsCount: 771, service: 'Data Entry Services',
    excerpt: 'Data entry, copy-paste, typing, PDF to Word/Excel and web research — delivered in as little as 24 hours.',
  },
  {
    title: 'I will provide targeted B2B lead generation, prospect and email list building',
    url: `${FIVERR_URL}/provide-b2b-lead-generation-prospect-research-and-business-list-building`,
    image: `${CDN}/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/502525015/original/44d64efe979ce61f7d9d09d97abc662f6c9d4519/provide-b2b-lead-generation-prospect-research-and-business-list-building.jpg`,
    startingPrice: 30, rating: 4.9, reviewsCount: 11, service: 'B2B Lead Generation',
    excerpt: 'Manually researched B2B prospects with verified business emails, built around your ideal customer.',
  },
  {
    title: 'I will do front end web development with React, responsive website design',
    url: `${FIVERR_URL}/do-front-end-web-development-with-react-responsive-website-design`,
    image: `${CDN}/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/487153398/original/f1d420c53ef9af292c75e9f4b5cf1f14a8818f06/do-front-end-web-development-with-react-responsive-website-design.jpg`,
    startingPrice: 80, rating: 5, reviewsCount: 4, service: 'Web Development',
    excerpt: 'Modern, fully responsive websites with React, Tailwind CSS and the MERN stack.',
  },
  {
    title: 'I will provide professional data entry, Excel and spreadsheet management',
    url: `${FIVERR_URL}/do-data-entry-copy-paste-web-research-quick-task`,
    image: `${CDN}/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/380911346/original/7a0ea7aae48879b5f9cb13b46ec0e7ef6cfebb21/do-data-entry-copy-paste-web-research-quick-task.jpg`,
    startingPrice: 100, rating: 5, reviewsCount: 8, service: 'Data Entry Services',
    excerpt: 'Up to 500 records with accurate data entry, Excel formatting, cleaning and spreadsheet organisation.',
  },
].map((g, i) => ({ ...g, platform: 'Fiverr', order: i }));

export const portfolio = [
  {
    title: 'Zeviro agency platform: website, CRM & client portal',
    slug: 'zeviro-agency-platform',
    clientName: 'Zeviro (in-house product)',
    platform: 'Direct',
    year: '2026',
    service: 'Web & Mobile App Development',
    industry: 'Professional Services',
    featured: true,
    image: '/images/portfolio/zeviro-website.jpg',
    gallery: ['/images/portfolio/zeviro-admin.jpg', '/images/portfolio/zeviro-portal.jpg'],
    externalUrl: 'https://zeviro.agency',
    excerpt: 'A full MERN platform: marketing website, online ordering, AI chatbot, live chat, CRM, team dashboard and a secure client portal with real-time messaging.',
    challenge: 'We needed one system to win clients and serve them: a fast website with online ordering, a CRM for leads and chats, project management for the team, and a private portal where clients follow their orders, files, messages and invoices.',
    solution: 'We designed and built a React + Node.js + MongoDB platform with role-based access for the super admin, team members and clients (each with its own login), Socket.IO for real-time chat, typing indicators and notifications, a knowledge-base AI assistant with human hand-off, service packages with checkout and invoices, and a light/dark theme.',
    results: ['Website, CRM and client portal in one codebase', 'Real-time messages, typing indicators & notifications', 'Online ordering with automatic invoices', 'Separate secure logins for clients, team and super admin'],
    technologies: ['React', 'Vite', 'Tailwind CSS', 'Node.js', 'Express', 'MongoDB', 'Socket.IO', 'JWT'],
  },
  {
    title: 'Zeviro Android app for clients and team',
    slug: 'zeviro-android-app',
    clientName: 'Zeviro (in-house product)',
    platform: 'Direct',
    year: '2026',
    service: 'Web & Mobile App Development',
    industry: 'Professional Services',
    featured: true,
    image: '/images/portfolio/zeviro-android.jpg',
    excerpt: 'One React Native app for visitors, clients and team members — sharing the same API and real-time backend as the website.',
    challenge: 'Clients wanted to check progress and reply to messages from their phones, and the team needed to answer live chats and leads on the go.',
    solution: 'We built an Expo / React Native app with role-aware navigation: visitors can browse services and chat with the AI assistant, clients see projects, messages, invoices and files, and team members manage leads and live chats. Tokens are stored in secure storage and every screen updates in real time.',
    results: ['One app for three audiences', 'Real-time chat and messages with typing indicators', 'Light, dark and system themes', 'Built with EAS for Google Play'],
    technologies: ['React Native', 'Expo', 'Expo Router', 'Socket.IO', 'Secure Store'],
  },
  {
    title: 'Data entry & web research deliveries',
    slug: 'data-entry-web-research-deliveries',
    clientName: 'Fiverr clients (details hidden)',
    platform: 'Fiverr',
    service: 'Data Entry Services',
    featured: true,
    image: `${CDN}/image/upload/t_smartwm/t_main1,q_auto,f_auto,q_auto,f_auto/v1/attachments/delivery/asset/97cc39b899b7767fc805d260f53ecd11-1786906416/Screenshot_2%20%281%29.png`,
    gallery: [
      `${CDN}/image/upload/t_smartwm/t_main1,q_auto,f_auto/v1/attachments/delivery/asset/e3b063f2c4872f4e8b55bcba20a4a9a2-1784543730/Screenshot_2.png`,
      `${CDN}/image/upload/t_smartwm/t_main1,q_auto,f_auto/v1/attachments/delivery/asset/e1eeaa556bdcf3b5f4447cbd01996a82-1715179835/Screenshot_5.png`,
    ],
    externalUrl: `${FIVERR_URL}/do-provide-all-type-data-entry-within-24hrs`,
    excerpt: 'Sample deliveries from our most popular Fiverr gig — structured spreadsheets built from web research, documents and directories.',
    challenge: 'Clients usually come to us with information scattered across websites, PDFs, images or directories that needs to become one clean, structured spreadsheet — accurately and fast.',
    solution: 'We agree on the exact columns and format, collect and enter the data manually, then check every row for accuracy and duplicates before delivering in Excel, Google Sheets or CSV.',
    results: ['Gig rating 4.8★ from 770+ reviews', 'Delivery from 24 hours', 'Quality check on every file'],
    technologies: ['Excel', 'Google Sheets', 'Web research'],
  },
  {
    title: 'React front-end websites',
    slug: 'react-front-end-websites',
    clientName: 'Fiverr clients',
    platform: 'Fiverr',
    service: 'Web Development',
    image: `${CDN}/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/487153398/original/f1d420c53ef9af292c75e9f4b5cf1f14a8818f06/do-front-end-web-development-with-react-responsive-website-design.jpg`,
    gallery: [`${CDN}/image/upload/t_smartwm/t_gig_pdf_gallery_view_ver4,q_auto,f_auto/v1/attachments/delivery/asset/5f44bc870e480a9e8f6cb87c82dc6058-1782066872/Projects%20page-1.pdf`],
    externalUrl: `${FIVERR_URL}/do-front-end-web-development-with-react-responsive-website-design`,
    excerpt: 'Responsive business and portfolio websites built with React and Tailwind CSS for clients through Fiverr — rated 5.0★.',
    challenge: 'Business owners needed modern, mobile-friendly websites — often from a Figma design or a reference site — delivered quickly and ready to connect to their domain.',
    solution: 'We build reusable React components styled with Tailwind CSS, optimise images and loading speed, and deliver clean code together with hosting setup help.',
    results: ['5.0★ gig rating', 'Figma-to-code with pixel-perfect layouts', 'Repeat clients (see reviews)'],
    technologies: ['React', 'Tailwind CSS', 'JavaScript', 'Node.js'],
  },
  {
    title: 'B2B prospect lists & email research',
    slug: 'b2b-prospect-lists',
    clientName: 'Fiverr clients',
    platform: 'Fiverr',
    service: 'B2B Lead Generation',
    image: `${CDN}/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/502525015/original/44d64efe979ce61f7d9d09d97abc662f6c9d4519/provide-b2b-lead-generation-prospect-research-and-business-list-building.jpg`,
    externalUrl: `${FIVERR_URL}/provide-b2b-lead-generation-prospect-research-and-business-list-building`,
    excerpt: 'Targeted prospect lists for sales teams — decision-makers by industry, location and job title with verified business emails.',
    challenge: 'Sales teams needed accurate contacts for specific roles and regions instead of generic, outdated databases.',
    solution: 'We research each contact manually on LinkedIn, company websites and business directories, verify business emails and deliver a de-duplicated, CRM-ready file.',
    results: ['4.9★ gig rating', 'Communication rated 5.0 by buyers', 'CRM-ready Excel / CSV / Sheets'],
    technologies: ['LinkedIn Sales Navigator', 'Apollo', 'Email verification', 'Google Sheets'],
  },
].map((c, i) => ({ ...c, order: i, body: `${c.challenge}\n\n${c.solution}` }));

// Real reviews left by buyers on Fiverr (exact text). Shown with the reviewer's username and country.
export const reviews = [
  ['awalkerpdv', 'United States', 'Data Entry Services', 'Appreciate him reaching out proactively to get the requirements. Was responsive when adjustments were requested. Would work with him again.'],
  ['thomasjp88', 'United Kingdom', 'Data Entry Services', 'His communication is brilliant and his attention to detail is excellent.'],
  ['crcouro81', 'United States', 'Data Entry Services', 'Followed the instructions well, showed a willingness to learn and adapt, and demonstrated a positive attitude throughout the process.'],
  ['hiimacks', 'United States', 'Data Entry Services', 'Very responsive, work was completed sooner than expected and accurately'],
  ['f_yousu', 'United States', 'Data Entry Services', 'Thanks for all the help in this task. This team works very reliably.'],
  ['smartdesktop', 'Israel', 'Web Development', 'Above expectation, very good communication we continue'],
  ['prmntplcmentllc', 'United States', 'Data Entry Services', 'Excellent work'],
  ['molly_fo', 'Netherlands', 'Data Entry Services', 'Always a pleasure.'],
  ['careiq', 'Canada', 'Data Entry Services', 'great work.'],
].map(([title, country, service, body], i) => ({ title, country, service, body, rating: 5, platform: 'Fiverr', sourceUrl: FIVERR_URL, verified: true, published: true, order: i }));
